### ISSUE TITLE
Support for newer version of Keras?

### ISSUE THREAD

**Issue by physicso** [qxcv/caffe2keras#1]
I have installed the newest version of Keras. The Error goes:
**TypeError: ('Keyword argument not understood:', 'dim_ordering')**
Can you please have a look at it?

**Comment by physicso** [comment]
Can you please give the Keras version you have used?

**Comment by qxcv** [comment]
I assume it was Keras 1.2.x. Keras 2 changed "dim_ordering" to "data_format". I'll have a look and see whether I can get it to work again.

**Comment by qxcv** [comment]
Looks like there are quite a few changes to be made. I fixed some of the more obvious warnings, but there are some subtle issues which will take a bit more work to debug. I can't do it now, but I can look into it later next week if you still need it.

**Comment by physicso** [comment]
Thank you very much! By the way, Keras 2.x added the dilation_rate parameter for Conv layers, which is common for FCN image segmentation models :)

**Comment by qxcv** [comment]
Should work with 2.0.6 now; tested on a [convolutional pose machine](https://github.com/shihenw/convolutional-pose-machines-release). I added some code for `dilation_rate`, but I don't have an appropriate model to test it on, so you may have to fiddle with `caffe2keras.convert.handle_conv()` if it doesn't work the first time.

**Comment by physicso** [comment]
Thanks! I will test it on my model and give you a feedback :)
